#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSOR_GP2AP)	+= gp2ap002.o
obj-$(CONFIG_SENSOR_BMA150)	+= bma150.o
obj-$(CONFIG_SENSOR_KR3DH)	+= kr3dh.o
obj-$(CONFIG_SENSOR_AK8973)	+= akm8973.o
obj-$(CONFIG_SENSOR_AMI602) += ami602.o

#sungmin.shin	10.07.30	
#add AVAGO digital proximity and ambient light sensor
obj-$(CONFIG_SENSOR_APDS9900) += apds9900.o
